# Generated by Django 5.1.4 on 2024-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_sistolica', models.FloatField()),
                ('pressao_diastolica', models.FloatField()),
                ('classificacao', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
